### ISSUE TITLE
Fabric 0.15.10 Compatibility

### ISSUE THREAD

**Issue by ereese99** [asasinmode/wheelbarrow#1]
Fabric 0.15.10 is out and it throws an error for this mod saying it's not compatible yet

Should be easy.

**Comment by asasinmode** [comment]
I tried the 1.20.4 version with fabric 0.15.10 and it worked fine. You might've been trying to use the mod on 1.20.5, which is now released on both [modrinth](https://modrinth.com/mod/wheelbarrow/version/xduWPNm4) and [curseforge](https://www.curseforge.com/minecraft/mc-mods/wheelbarrow/files/5288309).

Reopen if I'm mistaken and please provide the combination of

1. Minecraft version
2. Fabric loader version
3. Wheelbarrow mod version

That's not working

**Comment by ereese99** [comment]
@asasinmode 
Minecraft Version: 1.20.1
Fabric Loader Version: 0.15.10
Wheelbarrow Mod Version: 1.0.0

**Comment by asasinmode** [comment]
It seems to work for me. I made a new modpack in modrinth app, chose fabric `0.15.10` with minecraft `1.20.1`, added the wheelbarrow through add content and game worked fine. I also tried the jar downloaded from curseforge and there were no issues.

The mod file I'm working with is called `wheelbarrow-1.0.0+fabric_1.20.1.jar`. Are you having issues with the same one?

Could you maybe share the error logs you are getting?

**Comment by ereese99** [comment]
It's working now

not sure what changed, but it works!
