### ISSUE TITLE
Disconnect from server from mobs

### ISSUE THREAD

**Issue by CloverENBY** [asasinmode/wheelbarrow#2]
On a server I have with friends, whenever we put a mob in a wheelbarrow we get disconnected from the game (nothing happens when another player gets in the wheelbarrow though)

**Comment by asasinmode** [comment]
What mob is it? What error message pops up? What version? If it's a modpack, please link it. If there are error messages in console, please provide too

**Comment by nmackowiakk** [comment]
I also encounter this problem.
Here's what my console says: https://mclo.gs/HbLcliy
I tried with a sheep. When you come back, the entity is in, tho it kicks you again when you try to grip the wheelbarrow again. Unloading works just fine.
Here's the list of my server's mods: https://mclo.gs/hBtjnfU

**Comment by asasinmode** [comment]
I published [a new version](https://modrinth.com/mod/wheelbarrow/version/1.0.1) that should fix it. Let me know if it helped

**Comment by nmackowiakk** [comment]
It did! Thanks for creating this amazing mod btw. It helps so much with transporting these annoying villagers.
