### ISSUE TITLE
Not taking damage while riding with a wheelbarrow 

### ISSUE THREAD

**Issue by nmackowiakk** [asasinmode/wheelbarrow#3]
Just as stated in the title. It can be used to cheat a little while playing on a server.

**Comment by asasinmode** [comment]
What do you mean? I tested 1.20.6 and both the player controlling the wheelbarrow and the player being transported seem to be damagable by third player.

Is that not working on another version you are playing on (please tell which one) or is the player not damagable by something other than a player like lava/mobs?

**Comment by nmackowiakk** [comment]
The player doesn't take fall damage but I need to test it further. Perhaps it's caused by some of my server's mods.

**Comment by asasinmode** [comment]
This is intended, works same as boat. I'm not sure I want to change it but maybe I could be persuaded if people really want it.

**Comment by nmackowiakk** [comment]
Okay, that actually makes sense when you added boats in the context.
